//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Domain.Catalog.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookStore.Domain.Catalog.Core.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorId&apos;s first name.
        /// </summary>
        public static string Author_FirstName {
            get {
                return ResourceManager.GetString("Author_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorId&apos;s last name.
        /// </summary>
        public static string Author_LastName {
            get {
                return ResourceManager.GetString("Author_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorId of book.
        /// </summary>
        public static string Book_Author {
            get {
                return ResourceManager.GetString("Book_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of book.
        /// </summary>
        public static string Book_Image {
            get {
                return ResourceManager.GetString("Book_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isbn of book.
        /// </summary>
        public static string Book_Isbn {
            get {
                return ResourceManager.GetString("Book_Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of book.
        /// </summary>
        public static string Book_Price {
            get {
                return ResourceManager.GetString("Book_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicationDate of book.
        /// </summary>
        public static string Book_PublicationDate {
            get {
                return ResourceManager.GetString("Book_PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublisherId of book.
        /// </summary>
        public static string Book_Publisher {
            get {
                return ResourceManager.GetString("Book_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of book.
        /// </summary>
        public static string Book_Title {
            get {
                return ResourceManager.GetString("Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of category.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of publisher.
        /// </summary>
        public static string Publisher_Address {
            get {
                return ResourceManager.GetString("Publisher_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email of publisher.
        /// </summary>
        public static string Publisher_Email {
            get {
                return ResourceManager.GetString("Publisher_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of publisher.
        /// </summary>
        public static string Publisher_Name {
            get {
                return ResourceManager.GetString("Publisher_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number of publisher.
        /// </summary>
        public static string Publisher_PhoneNumber {
            get {
                return ResourceManager.GetString("Publisher_PhoneNumber", resourceCulture);
            }
        }
    }
}
